---

# TODO Consider adding Makefile. The Makefile can add the color vars and
# potentially have a single way of doing things for different CI pipelines. In
# addition a Makefile could be used to script running this on N distros if we
# get too many.

dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: centos-8-stream
    image: quay.io/centos/centos:stream8
    pre_build_image: true
  - name: ubuntu
    # TODO This is only a temporary measure until we get a better image.
    image: tanquetav/ubuntu-ansible:latest
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
